pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, this is Prasanna Jadhav'
                        echo 'We are in main branch'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
                  }
            }
            stage('Testing') {
                  steps {
                        echo "Testing a few cases"
                  }
            }
            stage('Deployment') {
                  steps {
                        echo "Deploying in Deployment Area"
                  }
            }
      }
